# Generated by Django 4.1 on 2024-05-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='account_info',
            field=models.CharField(max_length=128, verbose_name='账号信息'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.FloatField(verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='服务名称'),
        ),
        migrations.AlterField(
            model_name='service',
            name='platform',
            field=models.CharField(max_length=64, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='service',
            name='renewal_date',
            field=models.DateField(verbose_name='续订日期'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vendor',
            field=models.CharField(max_length=64, verbose_name='供应商'),
        ),
    ]
